// Generate the OpenCode configuration for this distribution.
//
// Everything is written into our own isolated config directory. OpenCode honours
// XDG_CONFIG_HOME and XDG_DATA_HOME on Windows (verified with `opencode debug
// paths`), so installing this product cannot disturb a user's existing OpenCode
// setup, and uninstalling it cannot take theirs with it.
//
// The model list is NEVER written into the config. The OmniRoute plugin fetches
// /v1/models at OpenCode startup, so the picker always shows what the gateway
// actually serves rather than a snapshot that rots.
import fs from "node:fs";
import path from "node:path";
import { PATHS, ensureDirs, pkg } from "../util/paths.mjs";
import { loadConfig, gatewayBaseUrl } from "../config.mjs";
import { locateOmniRoute } from "../gateway/locate.mjs";
import { logger } from "../util/log.mjs";

const log = logger("opencode-config");

export function ocConfigDir() {
  return PATHS.opencode;
}
export function ocDataDir() {
  return path.join(PATHS.home, "oc-data");
}

/**
 * Env that pins OpenCode to our directories. Used by every spawn of opencode.
 *
 * The two DISABLE flags matter more than they look. OpenCode auto-scans
 * ~/.claude/skills and ~/.agents/skills for external skills, so on a machine
 * that also runs Claude Code the user's entire personal skill library gets
 * loaded into this product's agent - unrelated skills, unrelated trigger words,
 * and a much larger prompt. Verified happening here before these were set.
 */
export function opencodeEnv(extra = {}) {
  return {
    ...process.env,
    XDG_CONFIG_HOME: PATHS.home,
    XDG_DATA_HOME: ocDataDir(),
    OMNI_AGENT_HOME: PATHS.home,
    PLAYWRIGHT_BROWSERS_PATH: PATHS.browsers,
    OPENCODE_DISABLE_EXTERNAL_SKILLS: "1",
    OPENCODE_DISABLE_CLAUDE_CODE_SKILLS: "1",
    // The OmniRoute plugin resolves auth.json from OPENCODE_DATA_DIR, falling
    // back to a hardcoded ~/.local/share/opencode - it does NOT read
    // XDG_DATA_HOME. Without this it cannot see the credential we just wrote,
    // logs "config shim skipped: no apiKey", and registers no models at all.
    OPENCODE_DATA_DIR: path.join(ocDataDir(), "opencode"),
    ...extra,
  };
}

function permissionProfile(name) {
  const all = JSON.parse(fs.readFileSync(pkg("config", "permissions.json"), "utf8"));
  const profile = all.profiles[name] ?? all.profiles.standard;
  const permission = structuredClone(profile.permission);

  // Allow the app's own directories through the external-directory boundary.
  //
  // Without this the agent researches successfully and then cannot save the
  // result: OpenCode classifies a write to its own workspace as "external"
  // whenever the resolved path differs from the worktree it computed - which
  // happens on Windows when LOCALAPPDATA is redirected into a packaged-app
  // LocalCache. In a headless `opencode run`, "ask" auto-rejects, so an hour of
  // work is discarded at the last step. Observed exactly that.
  //
  // Scoped to directories this product owns. The broad "*": "ask" stays first,
  // and OpenCode evaluates the LAST matching rule, so these are the exceptions.
  const glob = (p) => p.replace(/\\/g, "/").replace(/\/$/, "") + "/**";
  if (permission.external_directory !== "allow") {
    permission.external_directory = {
      "*": typeof permission.external_directory === "string" ? permission.external_directory : "ask",
      [glob(PATHS.workspace)]: "allow",
      [glob(PATHS.downloads)]: "allow",
      [glob(PATHS.home)]: "allow",
      // Name-based safety net for redirected filesystems.
      //
      // Under a Windows packaged (MSIX) app, writes to LOCALAPPDATA are
      // virtualised into the container's LocalCache. This process sees
      // ...\Local\OmniAgent\... while OpenCode sees
      // ...\Local\Packages\<pkg>\LocalCache\Local\OmniAgent\..., so the
      // absolute patterns above simply do not match and every write is refused.
      // Measured exactly that. These globs are still scoped to directories
      // named after this application.
      "**/OmniAgent/**": "allow",
      "**/OmniAgent Workspace/**": "allow",
    };
  }
  return permission;
}

/**
 * Install the plugin files.
 * The Omni Agent plugin is written as a one-line re-export shim pointing at the
 * real module inside the installation, so there is exactly one copy of the code
 * and no stale duplicate after an upgrade.
 */
function installPlugins() {
  const pluginsDir = path.join(ocConfigDir(), "plugins");
  fs.mkdirSync(pluginsDir, { recursive: true });

  const realPlugin = pathToFileUrl(pkg("plugin", "index.mjs"));
  fs.writeFileSync(
    path.join(pluginsDir, "omni-agent.js"),
    `// Generated by omni-agent setup. Re-exports the installed plugin.\n` +
      `export { OmniAgentPlugin } from ${JSON.stringify(realPlugin)};\n`
  );

  // OmniRoute ships its OpenCode plugin pre-built inside the npm package.
  // Copying it (rather than re-exporting) because OpenCode dedupes plugin loads
  // by module path and the upstream README asks for a real directory.
  const found = locateOmniRoute();
  let omniroutePlugin = null;
  if (found) {
    const src = path.join(found.root, "@omniroute", "opencode-plugin");
    if (fs.existsSync(path.join(src, "dist", "index.js"))) {
      const dest = path.join(pluginsDir, "omniroute");
      fs.mkdirSync(path.join(dest, "dist"), { recursive: true });
      fs.copyFileSync(path.join(src, "dist", "index.js"), path.join(dest, "dist", "index.js"));
      for (const f of ["package.json", "LICENSE"]) {
        if (fs.existsSync(path.join(src, f))) fs.copyFileSync(path.join(src, f), path.join(dest, f));
      }
      omniroutePlugin = "./plugins/omniroute/dist/index.js";
      log.info("installed omniroute opencode plugin", { version: found.version });
    }
  }
  return { omniroutePlugin };
}

function pathToFileUrl(p) {
  return new URL(`file:///${path.resolve(p).replace(/\\/g, "/")}`).href;
}

/** Copy the skill library into the OpenCode config dir. */
function installSkills() {
  const src = pkg("skills");
  const dest = path.join(ocConfigDir(), "skills");
  if (!fs.existsSync(src)) return 0;
  fs.rmSync(dest, { recursive: true, force: true });
  fs.cpSync(src, dest, { recursive: true });
  return fs.readdirSync(dest).length;
}

/** The always-loaded operating instructions for every agent. */
function installInstructions() {
  const src = pkg("config", "opencode", "AGENTS.md");
  const dest = path.join(ocConfigDir(), "AGENTS.md");
  if (fs.existsSync(src)) fs.copyFileSync(src, dest);
  return dest;
}

/**
 * Write opencode.json.
 * @param {{apiKey?:string|null}} [opts]
 */
export function writeOpenCodeConfig(opts = {}) {
  ensureDirs();
  const cfg = loadConfig();
  fs.mkdirSync(ocConfigDir(), { recursive: true });
  fs.mkdirSync(ocDataDir(), { recursive: true });

  const { omniroutePlugin } = installPlugins();
  const skillCount = installSkills();
  installInstructions();

  const baseURL = gatewayBaseUrl(cfg);

  const plugins = ["./plugins/omni-agent.js"];
  if (omniroutePlugin) {
    plugins.push([
      omniroutePlugin,
      {
        providerId: "omniroute",
        displayName: "Omni Agent Models",
        baseURL,
        autoSyncIntervalMs: 300000,
        modelCacheTtl: 300000,
        features: {
          // Register EVERY model the gateway can serve, not just the ones it
          // currently rates as healthy. `usableOnly: true` looks safer and is
          // not: measured 2026-08-28 the gateway's own catalogue held 188
          // models across 10 live providers while the filter registered 81, so
          // more than a hundred free models were unreachable from the picker
          // with no way for the user to ask for them.
          //
          // The tradeoff is real - an unhealthy model fails when it is chosen -
          // so the model picker marks which ones the gateway currently rates as
          // usable rather than hiding the rest.
          usableOnly: false,
          diskCache: true,
        },
      },
    ]);
  }

  // The plugin registers under `opencode-<providerId>`, not the bare id it is
  // given - so a model reference of "omniroute/..." resolves to nothing. Derive
  // the prefix rather than hardcoding either spelling.
  const providerPrefix = omniroutePlugin ? "opencode-omniroute" : "omniroute";

  // `small_model` is OpenCode's cheap path for titles and summaries, which is
  // exactly the token-budget behaviour we want - but referencing a provider
  // that fails to register makes OpenCode itself abort with
  // "undefined is not an object (evaluating '$.models')", taking the whole CLI
  // down. So it is only set when the wiring it depends on is actually present.
  const smallModelSafe = !!omniroutePlugin && !!opts.apiKey;

  // The agent's own model.
  //
  // Left unset, OpenCode picks one itself - observed choosing `oc/big-pickle`,
  // a specific free model - which means the routing preset the user selected
  // governs nothing the agent actually does. Pointing it at the gateway combo
  // for the configured mode is what makes "smart" and "cheap" mean something.
  //
  // Still not a hardcoded vendor model: it is a combo id, resolved from the live
  // catalogue by the caller, and the gateway does the real routing behind it.
  // OpenCode does not hot-reload config, so a mode change applies at next launch.
  const defaultModel = opts.defaultModel ? `${providerPrefix}/${opts.defaultModel}` : null;

  const config = {
    $schema: "https://opencode.ai/config.json",
    ...(defaultModel && smallModelSafe ? { model: defaultModel } : {}),
    ...(smallModelSafe ? { small_model: `${providerPrefix}/auto/cheap` } : {}),
    default_agent: "omni",
    autoupdate: false,
    share: "disabled",
    instructions: ["AGENTS.md"],
    skills: { paths: ["./skills"] },
    plugin: plugins,
    permission: permissionProfile(cfg.permissions.profile),
    tool_output: { max_lines: 400, max_bytes: 60000 },
    compaction: { auto: true, tail_turns: 15 },
    agent: {
      omni: {
        description:
          "General-purpose agent: coding, research, browsing, documents and data. The default.",
        mode: "primary",
        prompt:
          "You are Omni Agent. You can write and run code, browse the real web with a real browser, " +
          "search and read web pages, work with PDFs, spreadsheets and data files, and use Git.\n\n" +
          "Working rules:\n" +
          "- Verify before you assert. A search snippet is a lead; only web_fetch or the browser gives you " +
          "content you may quote or cite. Never state a URL you have not retrieved.\n" +
          "- Cite the FINAL url the tool reports, after redirects.\n" +
          "- Say what you do not know. Distinguish what a source said from what you inferred.\n" +
          "- Escalate deliberately: plain fetch, then scrape, then the real browser. The browser is slow; " +
          "do not reach for it when a fetch would do.\n" +
          "- Before any web form submission, or any action that sends, publishes, buys, applies or deletes, " +
          "stop and get the user's explicit go-ahead for that specific action.\n" +
          "- The user is often not a programmer. Explain what you did in plain language; keep the jargon in the code.",
      },
      research: {
        description: "Multi-source web research with verified citations. Use for questions needing several sources.",
        mode: "subagent",
        prompt:
          "You research questions across multiple independent sources and report findings with citations.\n" +
          "Search broadly, then FETCH each promising result - snippets are never sufficient evidence. " +
          "Prefer primary sources (an organisation's own site) over aggregators. Record the final URL for every " +
          "claim, note the date where the page gives one, and flag anything you could not verify. " +
          "Deduplicate results that are the same underlying item on different sites. " +
          "Never invent a URL, a deadline or an eligibility rule.",
        tools: { write: false, edit: false },
      },
      browse: {
        description: "Interactive browser work: logging in, filling forms, multi-step web flows.",
        mode: "subagent",
        prompt:
          "You drive a real browser to complete interactive web tasks.\n" +
          "Always take a snapshot before acting, and take a fresh one after anything that changes the page - " +
          "refs are invalidated by navigation. Fill fields one at a time and re-snapshot to confirm the values " +
          "actually landed before moving on. " +
          "NEVER submit a form, send a message, apply for anything or complete a purchase unless the user has " +
          "explicitly authorised that exact action. Filling a form and stopping before submission is the normal, " +
          "expected outcome - report the filled values and wait.",
      },
      code: {
        description: "Focused software work: writing, refactoring, debugging and testing code.",
        mode: "subagent",
        prompt:
          "You write and fix code. Read the surrounding code before changing it and match its style. " +
          "Make the smallest change that solves the problem. Run the tests, and report failures with the actual " +
          "output rather than a summary. If you cannot verify something works, say so plainly.",
      },
    },
  };

  const dest = path.join(ocConfigDir(), "opencode.json");
  fs.writeFileSync(dest, JSON.stringify(config, null, 2));
  log.info("wrote opencode config", { dest, skills: skillCount, omnirouteWired: !!omniroutePlugin });

  return {
    configPath: dest,
    configDir: ocConfigDir(),
    dataDir: ocDataDir(),
    skills: skillCount,
    omnirouteWired: !!omniroutePlugin,
    baseURL,
  };
}

/** Write the gateway credential into OpenCode's auth store, if we have one. */
export function writeOpenCodeAuth(apiKey) {
  if (!apiKey) return { written: false, reason: "no key" };
  const authFile = path.join(ocDataDir(), "opencode", "auth.json");
  fs.mkdirSync(path.dirname(authFile), { recursive: true });
  let auth = {};
  try {
    auth = JSON.parse(fs.readFileSync(authFile, "utf8"));
  } catch {}
  auth["opencode-omniroute"] = { type: "api", key: apiKey };
  fs.writeFileSync(authFile, JSON.stringify(auth, null, 2), { mode: 0o600 });
  return { written: true, authFile };
}
